### ISSUE TITLE
Nuget package for v2.124

### ISSUE THREAD

**Issue by skarred14** [Microsoft/Docker.DotNet#94] opened 2016-07-14 09:14 UTC
@ahmetalpbalkan: Nuget package currently is at v1.2. Most of the new and useful calls around exec, resize and attach are referenced in the latest package. Any updates on when the nuget package would be updated? Question arises because cloning the repo does not address all the missing libraries needed for a successful execution of the project. Although I updated references based on the project.json file, I still am receiving build errors around 'The type 'Object' is defined in an assemby that is not referenced. You must add a reference to System.Runtime Version 4.0.0.0..', 'httpresponseheaders does not contain a definition for TryWithoutValidation'. Suggestions?

**Comment by ahmetalpbalkan** [comment] 2016-07-14 20:20
duplicate of #88.

**Comment by skarred14** [comment] 2016-07-14 20:57
thanks for addressing this issue. Meanwhile, I am trying to git clone the repo into my visual studio project. I have downloaded quite a few dependencies including Bcl (including async), Asp.Net Web API, Newtonsoft, and references accordingly. The few errors I am unable to avoid during build are below. Any suggestions would be great (currently i am targetting 4.5.2 framework)
DockerClient.cs: (Error: Cannot convert from int to string, NamedPipeClientStream does not contain a definition for 'ConnectAsync'and the best extension is requires TcpClient)
"await stream.ConnectAsync(timeout, cancellationToken);"
DockerPipeStream.cs: (Error: EventWaitHandle doesnt have a definition for GetSafeHandle()
HttpConnection.cs: (Error: HttpResponseHeaders does not contain a definition for TryAddWithoutValidation):
if (!response.Headers.TryAddWithoutValidation(headerName, headerValue))
                {
                    bool success = response.Content.Headers.TryAddWithoutValidation(headerName, headerValue);
                    bool c = response.Content.Headers.AddWithoutValidation()
                    System.Diagnostics.Debug.Assert(success, "Failed to add response header: " + rawHeader);
                }

**Comment by jterry75** [comment] 2016-07-14 21:02
Are you building from dotnet cli? I created a net45 test project that works just fine. We explicitly cross compile Docker.DotNet for netstandard1.3; net46; and net45 at the moment. You should be able to use the net45 PCL target on any machine that has net45 installed with no additional dependencies that arent part of the framework itself.

**Comment by skarred14** [comment] 2016-07-14 21:17
Here are the steps I followed: 
1. Create new project with an empty web form based on an ASP.NET template
2. Add all docker.dotnet directory files (excluded basicauth and authx509) to App_Code folder from a local directory which has the git repo cloned, and set buildaction to compile
3. Add a dummy asp.net page with a basic call to list containers. Upon build I notice many errors. After installing the dependencies listed in the previous post. Could you please suggest if there is a list of steps I could follow to build the repo without errors?

**Comment by jterry75** [comment] 2016-07-14 21:19
What version of VS are you using? You will need 2015 Update 3 in order to build this project that way. Alternatively you can build with the dotnet cli then take the built binary and add it to the Reference Assemblies of your web project

**Comment by skarred14** [comment] 2016-07-14 21:27
I had updated to 2015 Update 3. Instead of adding DockerDotNet Repo files to my project - i am going ahead and using the solution file that has been included in the repo. as of now the references are getting restored, and after thats done and built i ll compare with my custom solution project to this one.

**Comment by skarred14** [comment] 2016-07-15 17:24
FInally, after some debugging I found the issue. For some reason, I am unable to register Docker.DotNet dll that gets generated even after using strong assembly name and providing the path to the .snk file in assemblyinfo.cs. Using the relatively straightforward approach, following packages are needed to do a custom add of the Docker.DotNet repo: Newtonsoft, Microsoft Bcl (including Bcl Async), System.Buffers, System.Net.Http.FOrmatting.Extension, Microsoft ASPNET Web API, System.Runtime.Serialization, System.Net. At this point, the line in DockerPipeStream.cs needed to be changed:
#if true //NET45
            handle = _event.SafeWaitHandle;
#else
            handle = _event.GetSafeWaitHandle();
#endif.
Any suggestions on registering assembly?

**Comment by jterry75** [comment] 2016-07-15 17:59
Do you mean "register to the GAC"? Yes you cannot register an assembly to the GAC without a strong name.

As far as your code change can you please help me to understand what you are doing? I don't understand how the code compiles for .NET 45 if your saying it needs an `#ifdef` for NET45 specifically. What is the behavior that doesn't work so I can give this a shot?

**Comment by skarred14** [comment] 2016-07-15 19:40
Yes, i was trying to use the gac utility to build the assembly file, but i have been getting a "Failure to load assembly" for the Docker.DotNet dll file. When I tried on a different project, I have been able to load the assembly of the other project. Not sure, what I am missing - created the snk file in the same directory as the Docker.DotNet dll. Will research further and see - if there are any recommendations, it would be helpful. 
With regards to the #ifdef, the original snipper in the DockerPipeStream.cs was:
#if NET45
 handle = _event.SafeWaitHandle;
 #else
 handle = _event.GetSafeWaitHandle();
 #endif.
During compile of the project, the build failed at the #else clause with the following errors: Error: EventWaitHandle doesnt have a definition for GetSafeHandle(). Similar error occurs in the DockerClient file as well: HttpResponseMessage does not contain a definition for ConnectAsync.
#if NET45
                        await Task.Run(() => stream.Connect(timeout), cancellationToken);
#else
                        await stream.ConnectAsync(timeout, cancellationToken);
#endif
                        return dockerStream;
In both the cases, if i comment out 'NET45' and have 'true' as in the previous comment for the #if directive, it works fine.

**Comment by jterry75** [comment] 2016-07-15 21:11
@skarred14 - I apologize, we seem to be talking past each other still. We build as part of our appveyor a build for net45, net46, and netstandard1.3. Because this currently builds with no issues I don't think an `#ifdef` is required on our side. It is likely that because you are trying to build for source you somewhere have changed one of the dependencies that are being included. The new dotnet cli structures are quite complicated unfortunately and this is very easy to do.

On a side note: I actually just published to NuGet the official release of the v2.124.1 Docker.DotNet. You should now be able to use this without needing to build any source. Can you try this in your project as a NuGet dependency without building it yourself and tell me if you are still seeing a build issue with just your code? I will create a net45 test project to make sure that this does indeed work on my side.

**Comment by skarred14** [comment] 2016-07-16 19:13
@jterry75 - sorry, i should have clarified the context. when i used the Dockerdotnet.sln file as is, the build went fine. I guess, to your point, I may have not installed the basic dependencies needed for the files to compile. thanks for uploading the nuget package. Possibly, if I were to follow the dependencies listed here and tested, it would work fine. I have just created a new project with just installing the v2.124.1 Docker.DotNet and there seems to be an issue with installing the package - error snippet below:
--------------------------------------------------------------------------------------------------
Executing nuget actions took 13.45 sec
Install-Package : Failed to add reference. The package 'Docker.DotNet' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This 
is possibly a bug in the package. Please contact the package owners for assistance.
At line:1 char:1
+ Install-Package Docker.DotNet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:02:55.0176772
--------------------------------------------------------------------------------------------------
Any suggestions on how I could get around this issue? I am using VS 2015 Community Edition (Update 3) to create .NET4.5 framework based web application.

**Comment by jterry75** [comment] 2016-07-18 18:02
What version of nuget are you running?

**Comment by playachronix** [comment] 2016-07-22 12:28
@jterry75 I am having the same issue with VS 2015 Update 3 (Enterprise) + NuGet v3.4.4.1321  I also updated to the NuGet url https://api.nuget.org/v3/index.json as recommended on the NuGet website https://www.nuget.org/.

**Comment by jterry75** [comment] 2016-07-22 15:52
@playachronix - Very interesting. I just tried this from VS targeting a downlevel moniker (.NET 451) and if fails have you are saying. Using a .NET Core project type though but still targeting the downlevel moniker works just fine. Also using dotnet cli works just fine. I will see what I can do to get the standard *.csproj style projects working.

Also, just FYI any reason for .NET 451? (JW)

**Comment by playachronix** [comment] 2016-07-22 16:33
@jterry75 Our project is .NET 4.5.  The solution has a bunch of projects for applications that run under mono in production.  Since sometimes mono sometimes doesn't have full support, it's easier to stick with the working version rather than bump to each .NET framework as it comes out.  At least we finally got VS 2015 vs 2010 :) In general I was hoping it would just work with a NuGet install (1.2.2 works fine) so it is easier for the handful of developers that use this solution to get the benefits without installing other applications or libraries.  I don't think it's the end of the world to need VS 2015 v3, it's just another half hour step that a dozen developers need to do to just get their work done.

**Comment by playachronix** [comment] 2016-07-22 16:35
@jterry75 I did try to get the source and open it to no avail (I don't have .NET core installed, it currently says I don't have VS 2015 v 3 properly installed, though I did that).  We just want some access to docker labels and other stuff added since the last version 1.2.2 :)

**Comment by jterry75** [comment] 2016-07-22 16:47
@skarred14 @playachronix - I just submitted a PR for #105. Can you give this a shot and tell me if it solves your problems. I tried this with both .NET 451 and .NET 46 *.csproj projects as well as dotnet cli. This should be what you need.

**Comment by playachronix** [comment] 2016-07-25 15:37
@jterry75 I can build it now and it seems to work.  I'm not sure what I needed .NET CORE for but installing it isn't the worst thing in the world.

**Comment by jterry75** [comment] 2016-07-25 23:21
@playachronix - Thanks for the confirmation! Working on merging this now.

P.S. - You normally wouldn't need .NET Core once this fix is published to nuget.org its just to build it locally requires that because it targets all the frameworks.

**Comment by skarred14** [comment] 2016-08-14 22:17
@jterry75 thanks for the update and apologies for the delayed response. i had stepped away into working out python scripts to interact with the docker containers with the earlier version. i just pulled the latest nuget package(2.124.1) and tested on both .NET4.5 and 4.6 frameworks on VS 2015. Everything worked fine - able to make the calls to the containers without running into issues with IronPython and MSScripting references within the project. thanks a lot for all the effort that must have gone into this issue.

**Comment by jterry75** [comment] 2016-08-15 17:32
@skarred14 - No worries. I'm glad that its working for you. Keep giving us feedback. We appreciate it.

**Closed by jterry75** 2016-08-15 17:32 UTC
Labels: question
